[book]
authors = ["Seasawher"]
language = "en"
multilingual = false
src = "src"
title = "Lean4 タクティク逆引きリスト"

[build]
create-missing = false
build-dir = "book"

[output.html]
additional-js = ["highlight.js"]
no-section-label = true