[book]
authors = ["Seasawher"]
language = "ja"
multilingual = false
src = "src"
title = "Lean4 タクティク逆引きリスト"

[build]
create-missing = false
build-dir = "book"

[output.html]
additional-js = ["assets/leanweb.js", "assets/fzf.umd.js", "assets/elasticlunr.js"]
no-section-label = true
git-repository-url = "https://github.com/lean-ja/tactic-cheetsheet"