[book]
authors = ["Seasawher"]
language = "zh"
multilingual = false
src = "src"
title = "Lean4 Tactic CheatSheet"
description = "Lean4 Tactic CheatSheet."

[build]
create-missing = false
build-dir = "book"

[output.html]
additional-js = ["assets/blockPlay.js", "assets/filePlay.js", "assets/fzf.umd.js", "assets/elasticlunr.js"]
no-section-label = true
git-repository-url = "https://github.com/Eric-Song-Nop/tactic-cheatsheet"
edit-url-template = "https://raw.githubusercontent.com/Eric-Song-Nop/tactic-cheatsheet/main/{path}"
