name: Links (Fail Fast)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          fail: true
